# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 152e27aa3793c345a0d4f5fb48a5f3e17e69aee53a9251c7eb2301f7fc6e9715870e9e73d805b84d3fffee237d62fcc7b129d7ff5a2fd0792159dfee2601d55f

test:
  secret_key_base: 9e1159075e8e86c77b2ebcd295a5df6cd98612ab0f760889bd7b2f5cb9894adc214c2e16f1d4594330ff1ba68aa88963e8daac852b931e743619561b31dd5c59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
